---
- name: Run bash script
  command: sudo bash ./flask_app/docker-install-ubuntu.sh
  register: result

- name: Wait until script finishes
  wait_for:
    path: ./flask_app/docker-install-ubuntu.sh
    search_regex: "script finished"
    state: present
  when: result|success
  
- name: Run bash script
  command: sudo bash ./flask_app/buildRunDocker.sh
  register: result


- name: Build Docker image for Flask app
  command: sudo docker build -t flask_app:latest ./flask_app

- name: Run Docker container for Flask app
  command: sudo docker run -d -p 5000:5000 --name flask_app_container flask_app:latest

- name: Check if Docker container is running
  shell: sudo docker ps | grep flask_app_container
  register: container_status
  ignore_errors: yes

- name: Ensure the Docker container is running
  assert:
    that:
      - container_status.rc == 0
    fail_msg: "The Docker container is not running."